import {
  StudentProfile,
  AcademiaProfile,
  IndustryProfile,
  SkillCategory,
  SkillAssessmentQuestion,
  LearningRecommendation,
  CareerPath,
  ProjectShowcase,
  Internship,
  JobOpportunity,
  InternshipApplication,
  PlacementApplication,
  WeeklyProgressLog,
  AppNotification,
  PortalDocument,
  CandidateCandidate,
  LiveMentorshipProject,
  TrainingProgram,
} from './types';

export const mockStudentProfile: StudentProfile = {
  id: 'stu-26044-01',
  name: 'Aarav Sharma',
  email: 'aarav.sharma@sih2026.edu.in',
  role: 'student',
  avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
  college: 'National Institute of Technology, Trichy',
  department: 'Computer Science & Engineering',
  rollNo: '2023CS26044',
  graduationYear: 2027,
  cgpa: 8.82,
  bio: 'Passionate computer science undergraduate focusing on distributed systems, full-stack engineering, and applied machine learning. SIH 2026 active contributor.',
  phone: '+91 98451 26044',
  location: 'Tiruchirappalli, Tamil Nadu',
  verifiedStatus: true,
  overallSkillScore: 86,
  skills: [
    { name: 'React & TypeScript', level: 90, verified: true, domain: 'Frontend Engineering' },
    { name: 'Node.js & Express', level: 85, verified: true, domain: 'Backend Engineering' },
    { name: 'Python & PyTorch', level: 80, verified: true, domain: 'AI & Data Science' },
    { name: 'PostgreSQL & SQL', level: 82, verified: true, domain: 'Databases' },
    { name: 'Docker & Kubernetes', level: 72, verified: false, domain: 'Cloud & DevOps' },
    { name: 'System Design & DSA', level: 88, verified: true, domain: 'Core CS' },
    { name: 'API Security & OAuth', level: 75, verified: true, domain: 'Cybersecurity' },
  ],
  githubUrl: 'https://github.com/aarav-sharma-26044',
  linkedinUrl: 'https://linkedin.com/in/aarav-sharma-sih',
  portfolioUrl: 'https://aarav-sih26.dev',
};

export const mockAcademiaProfile: AcademiaProfile = {
  id: 'acad-26044-01',
  name: 'Dr. Meenakshi Sundaram',
  email: 'm.sundaram@nitt.edu',
  role: 'academia',
  avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
  institutionName: 'National Institute of Technology, Trichy',
  department: 'Department of Computer Science & Engineering',
  designation: 'Professor & Dean of Industry-Academia Partnerships',
  aicteCode: 'AICTE-TN-ENGG-26044',
  employeeId: 'NITT-FAC-4891',
  phone: '+91 431 2503000',
  location: 'Tiruchirappalli, Tamil Nadu',
  researchInterests: ['Distributed Computing', 'AI for Education', 'Curriculum Industry Alignment', 'Next-Gen Networks'],
  totalStudentsMonitored: 840,
};

export const mockIndustryProfile: IndustryProfile = {
  id: 'ind-26044-01',
  name: 'Vikramaditya Sengupta',
  email: 'vikram.sengupta@bharattech.in',
  role: 'industry',
  avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
  companyName: 'Bharat Cloud & AI Innovations Ltd.',
  sector: 'Deep Tech & Enterprise Cloud Software',
  designation: 'VP of Engineering & Global Campus Talent',
  cinOrId: 'CIN-U72900KA2018PTC112345',
  phone: '+91 80 4600 2604',
  headquarters: 'Bengaluru, Karnataka',
  website: 'https://bharattechinnovations.in',
  activePostingsCount: 14,
};

export const mockSkillCategories: SkillCategory[] = [
  { id: 'sc-1', name: 'Full Stack & Web Architectures', icon: 'Code', currentProficiency: 88, industryDemand: 94, gap: 6, verifiedCount: 3 },
  { id: 'sc-2', name: 'Generative AI & Machine Learning', icon: 'Brain', currentProficiency: 76, industryDemand: 96, gap: 20, verifiedCount: 2 },
  { id: 'sc-3', name: 'Cloud Native & DevOps (Kubernetes/Docker)', icon: 'Cloud', currentProficiency: 68, industryDemand: 91, gap: 23, verifiedCount: 1 },
  { id: 'sc-4', name: 'Database Engineering & Distributed Systems', icon: 'Database', currentProficiency: 82, industryDemand: 89, gap: 7, verifiedCount: 2 },
  { id: 'sc-5', name: 'Embedded Systems & Industrial IoT', icon: 'Cpu', currentProficiency: 62, industryDemand: 78, gap: 16, verifiedCount: 1 },
  { id: 'sc-6', name: 'Information Security & Compliance', icon: 'Shield', currentProficiency: 70, industryDemand: 88, gap: 18, verifiedCount: 2 },
];

export const mockAssessmentQuestions: Record<string, SkillAssessmentQuestion[]> = {
  'Full Stack': [
    {
      id: 'q-fs-1',
      domain: 'Full Stack',
      question: 'Which HTTP header is essential for preventing cross-site scripting (XSS) attacks by strictly controlling where executable resources can load?',
      options: ['Content-Security-Policy', 'Access-Control-Allow-Origin', 'X-Frame-Options', 'Strict-Transport-Security'],
      correctIndex: 0,
      explanation: 'Content-Security-Policy (CSP) is a critical defensive HTTP header that restricts scripts, styles, and other resources to trusted origins.',
      difficulty: 'Intermediate',
    },
    {
      id: 'q-fs-2',
      domain: 'Full Stack',
      question: 'In React 18 and 19, how does automatic batching impact multiple state updates triggered inside asynchronous callbacks like setTimeout or fetch?',
      options: [
        'They still trigger multiple separate re-renders',
        'They are automatically batched into a single unified re-render pass',
        'Automatic batching only works in React Class components',
        'It requires calling ReactDOM.flushSync manually to work'
      ],
      correctIndex: 1,
      explanation: 'React 18+ introduced automatic batching across all asynchronous event handlers, timeouts, and promises, grouping state updates into a single re-render.',
      difficulty: 'Intermediate',
    },
    {
      id: 'q-fs-3',
      domain: 'Full Stack',
      question: 'When implementing database connection pooling in high-throughput Node.js microservices, what is the primary purpose of idle timeouts?',
      options: [
        'To speed up active queries',
        'To release inactive database connections and avoid resource leaks on the database server',
        'To encrypt data in flight',
        'To bypass ACID compliance constraints'
      ],
      correctIndex: 1,
      explanation: 'Idle timeouts terminate and clean up unused pooled connections so that database connection limits are not exceeded under varying loads.',
      difficulty: 'Advanced',
    },
    {
      id: 'q-fs-4',
      domain: 'Full Stack',
      question: 'Which CSS layout system is best suited for 2-dimensional layouts (handling both rows and columns simultaneously)?',
      options: ['CSS Flexbox', 'CSS Grid Layout', 'Float positioning', 'Table layout'],
      correctIndex: 1,
      explanation: 'CSS Grid is inherently two-dimensional, managing both row and column tracks simultaneously.',
      difficulty: 'Beginner',
    },
  ],
  'AI & ML': [
    {
      id: 'q-ai-1',
      domain: 'AI & ML',
      question: 'In Transformer architectures, what is the mathematical purpose of the Attention mechanism scaling factor 1 / sqrt(d_k)?',
      options: [
        'To speed up matrix multiplication by 50%',
        'To prevent dot products from growing excessively large, which pushes softmax into vanishing gradient regions',
        'To normalize the output to zero mean and unit variance',
        'To convert continuous tokens into discrete embeddings'
      ],
      correctIndex: 1,
      explanation: 'Scaling by the square root of the key dimension counters large dot products that would otherwise cause softmax gradients to become exponentially small.',
      difficulty: 'Advanced',
    },
    {
      id: 'q-ai-2',
      domain: 'AI & ML',
      question: 'Which evaluation metric is most appropriate for assessing a classification model on severely imbalanced fraud or anomaly datasets?',
      options: ['Accuracy', 'Area Under the Precision-Recall Curve (PR-AUC)', 'Mean Squared Error', 'Adjusted R-Squared'],
      correctIndex: 1,
      explanation: 'PR-AUC focuses specifically on the minority positive class without being inflated by true negatives.',
      difficulty: 'Intermediate',
    },
    {
      id: 'q-ai-3',
      domain: 'AI & ML',
      question: 'What technique allows running fine-tuning on large language models by updating low-rank decomposition matrices rather than all base model weights?',
      options: ['LoRA (Low-Rank Adaptation)', 'Dropout', 'Batch Normalization', 'Stochastic Gradient Descent'],
      correctIndex: 0,
      explanation: 'LoRA freezes pre-trained weights and injects trainable low-rank decomposition matrices into each layer, dramatically reducing VRAM and parameter count.',
      difficulty: 'Intermediate',
    },
  ],
  'Cloud & DevOps': [
    {
      id: 'q-cloud-1',
      domain: 'Cloud & DevOps',
      question: 'In Kubernetes, what is the primary role of an Ingress Controller?',
      options: [
        'To manage the physical hardware nodes',
        'To route external HTTP/HTTPS traffic into internal cluster ClusterIP services based on path or host rules',
        'To monitor CPU temperature of worker pods',
        'To backup persistent volume claims to S3 storage'
      ],
      correctIndex: 1,
      explanation: 'An Ingress Controller fulfills Ingress rules, acting as the reverse proxy and load balancer directing inbound traffic to cluster services.',
      difficulty: 'Intermediate',
    },
    {
      id: 'q-cloud-2',
      domain: 'Cloud & DevOps',
      question: 'Which Infrastructure as Code (IaC) concept describes maintaining a single source of truth in Git where declarative states are automatically synchronized to the cluster?',
      options: ['Imperative scripting', 'GitOps (e.g., ArgoCD / Flux)', 'Shadow IT', 'Monolithic provisioning'],
      correctIndex: 1,
      explanation: 'GitOps uses Git repositories as the single source of truth for declarative infrastructure and continuous automated reconciliation.',
      difficulty: 'Intermediate',
    },
  ],
};

export const mockLearningRecommendations: LearningRecommendation[] = [
  {
    id: 'lr-1',
    title: 'Cloud Native Microservices Architecture & Kubernetes',
    provider: 'NPTEL & AICTE Skill Council',
    domain: 'Cloud & DevOps',
    duration: '6 Weeks (Self-paced)',
    level: 'Intermediate',
    rating: 4.8,
    studentsEnrolled: 14200,
    badgeEarned: 'Certified Cloud Architect Associate',
    directUrl: 'https://swayam.gov.in/courses/cloud-microservices-sih',
    syllabusCovered: ['Containerization with Docker', 'Kubernetes Pod Lifecycle & Helm', 'Service Mesh (Istio)', 'CI/CD Pipelines with GitHub Actions'],
  },
  {
    id: 'lr-2',
    title: 'Practical Generative AI & Retrieval-Augmented Generation (RAG)',
    provider: 'IIT Madras & Industry Co-op',
    domain: 'AI & Data Science',
    duration: '8 Weeks',
    level: 'Advanced',
    rating: 4.9,
    studentsEnrolled: 8900,
    badgeEarned: 'Applied GenAI Practitioner',
    directUrl: 'https://nptel.ac.in/courses/applied-rag-genai',
    syllabusCovered: ['Vector Databases (Qdrant/Milvus)', 'Embedding Models & Cosine Distance', 'Chunking & Hybrid Search', 'Evaluation with RAGAS'],
  },
  {
    id: 'lr-3',
    title: 'High Performance Distributed Systems & Database Sharding',
    provider: 'SWAYAM National Portal',
    domain: 'Databases & Distributed Systems',
    duration: '5 Weeks',
    level: 'Intermediate',
    rating: 4.7,
    studentsEnrolled: 6300,
    badgeEarned: 'Distributed Systems Specialist',
    directUrl: 'https://swayam.gov.in/courses/distributed-systems',
    syllabusCovered: ['CAP Theorem & PACELC', 'Raft & Paxos Consensus', 'Consistent Hashing & Partitioning', 'Write-Ahead Logging (WAL)'],
  },
  {
    id: 'lr-4',
    title: 'Secure Full Stack Web Development & OWASP Top 10',
    provider: 'C-DAC & National Cyber Security Division',
    domain: 'Cybersecurity',
    duration: '4 Weeks',
    level: 'Beginner',
    rating: 4.6,
    studentsEnrolled: 11400,
    badgeEarned: 'Web Security Defense Certified',
    directUrl: 'https://cdac.in/cyber-defense-web',
    syllabusCovered: ['JWT Security & Refresh Token Rotation', 'CSRF, SSRF & Injection Mitigation', 'Rate Limiting & DDoS Resiliency', 'Zero Trust Architecture'],
  },
];

export const mockCareerPaths: CareerPath[] = [
  {
    id: 'cp-1',
    roleName: 'Full Stack Cloud Platform Engineer',
    avgCtcRange: '₹9.5 - ₹18.0 LPA',
    marketDemand: 'Very High',
    description: 'Designs and builds resilient enterprise microservices, scalable distributed APIs, and performant web applications with automated cloud deployments.',
    matchingScore: 88,
    requiredSkills: ['React/TypeScript', 'Node.js/Go', 'PostgreSQL', 'Docker/Kubernetes', 'CI/CD Pipelines', 'System Design'],
    gapSkills: ['Kubernetes Cluster Admin', 'Distributed Tracing (OpenTelemetry)'],
    milestones: [
      { title: 'Foundational Data Structures & Concurrency', description: 'Master trees, graphs, threading, and event-loop internals.', completed: true },
      { title: 'Full Stack Enterprise API Development', description: 'Build scalable REST & GraphQL services with connection pools.', completed: true },
      { title: 'Production Cloud Orchestration', description: 'Deploy microservices into managed Kubernetes with automated health checks.', completed: false },
      { title: 'Industry Capstone & Mentorship', description: 'Complete a live industrial problem statement verified by partner company.', completed: false },
    ],
  },
  {
    id: 'cp-2',
    roleName: 'AI & Machine Learning Engineer',
    avgCtcRange: '₹12.0 - ₹24.0 LPA',
    marketDemand: 'Very High',
    description: 'Develops and fine-tunes domain-specific LLMs, production RAG pipelines, computer vision systems, and integrates scalable inference engines.',
    matchingScore: 78,
    requiredSkills: ['Python', 'PyTorch', 'Vector DBs', 'RAG Pipelines', 'Transformers', 'FastAPI'],
    gapSkills: ['Quantization & vLLM Serving', 'Agentic Workflow Orchestration (LangGraph)'],
    milestones: [
      { title: 'Math Foundations & Classical ML', description: 'Linear algebra, calculus, regression, and tree-based ensembles.', completed: true },
      { title: 'Deep Learning & Neural Networks', description: 'CNNs, RNNs, and custom PyTorch training loops.', completed: true },
      { title: 'Transformer Fine-tuning & LoRA', description: 'Supervised fine-tuning and parameter-efficient adaptation.', completed: false },
      { title: 'Production AI Deployment & MLOps', description: 'Model registry, low-latency streaming endpoints, and monitoring.', completed: false },
    ],
  },
  {
    id: 'cp-3',
    roleName: 'Cybersecurity & Application Security Analyst',
    avgCtcRange: '₹8.5 - ₹16.5 LPA',
    marketDemand: 'High',
    description: 'Audits software codebases for zero-day vulnerabilities, architects secure authentication pipelines, and enforces compliance protocols.',
    matchingScore: 72,
    requiredSkills: ['Network Security', 'OWASP Top 10', 'Penetration Testing', 'Cryptography', 'SIEM Tools'],
    gapSkills: ['Reverse Engineering', 'Burp Suite Pro Advanced Scripting'],
    milestones: [
      { title: 'Core Networking & Packet Analysis', description: 'TCP/IP handshake, TLS 1.3 encryption, and Wireshark forensics.', completed: true },
      { title: 'Web Vulnerability Assessment', description: 'Practical exploitation and patching of SQLi, XSS, and SSRF.', completed: true },
      { title: 'Enterprise Red-Teaming & Threat Modeling', description: 'STRIDE modeling and automated static code analysis (SAST).', completed: false },
      { title: 'Incident Response & SOC Protocols', description: 'Log correlation and automated playbooks for containment.', completed: false },
    ],
  },
];

export const mockProjects: ProjectShowcase[] = [
  {
    id: 'proj-1',
    title: 'Suraksha: AI-Powered Edge Video Analytics for Railway Crossings',
    description: 'SIH 2026 pre-prototype detecting unmanned obstacle intrusions with 98.4% precision using optimized YOLOv8 on NVIDIA Jetson with real-time station alerts.',
    domain: 'Computer Vision & IoT',
    technologies: ['PyTorch', 'YOLOv8', 'FastAPI', 'MQTT', 'React', 'Docker'],
    liveUrl: 'https://suraksha-rail.sih2026.in',
    repoUrl: 'https://github.com/aarav-sharma-26044/suraksha-edge',
    verifiedByMentor: true,
    mentorName: 'Dr. Meenakshi Sundaram (NIT Trichy)',
    completionDate: 'Jan 2026',
    starsOrLikes: 142,
  },
  {
    id: 'proj-2',
    title: 'VaniSetu: Multilingual Voice-First Agritech Advisory',
    description: 'Speech-to-speech assistant supporting 12 Indic languages, helping rural farmers query mandi rates and crop disease diagnostics via offline-first microservices.',
    domain: 'Generative AI & Audio',
    technologies: ['Whisper Indic', 'LangChain', 'PostgreSQL', 'Tailwind', 'Python'],
    liveUrl: 'https://vanisetu.sih2026.in',
    repoUrl: 'https://github.com/aarav-sharma-26044/vani-setu',
    verifiedByMentor: true,
    mentorName: 'Vikramaditya Sengupta (Bharat Cloud)',
    completionDate: 'Feb 2026',
    starsOrLikes: 89,
  },
  {
    id: 'proj-3',
    title: 'BlockVerify: Tamper-Proof Academic Credential Ledger',
    description: 'Decentralized document verification engine enabling instant validation of university marksheets, degree certificates, and industry internships.',
    domain: 'Distributed Systems & Security',
    technologies: ['Solidity', 'Ethers.js', 'Node.js', 'IPFS', 'TypeScript'],
    liveUrl: 'https://blockverify-edu.sih2026.in',
    repoUrl: 'https://github.com/aarav-sharma-26044/block-verify',
    verifiedByMentor: false,
    completionDate: 'Dec 2025',
    starsOrLikes: 57,
  },
];

export const mockInternships: Internship[] = [
  {
    id: 'int-1',
    title: 'Cloud Systems & Distributed Cache Engineering Intern',
    company: 'Bharat Cloud & AI Innovations Ltd.',
    companyLogo: 'https://images.unsplash.com/photo-1516321318423-f06f85e504b3?w=100&auto=format&fit=crop&q=80',
    location: 'Bengaluru / Hybrid',
    type: 'Hybrid',
    duration: '6 Months (Jul 2026 - Dec 2026)',
    stipend: '₹45,000 / month',
    openings: 8,
    deadline: '2026-09-30',
    domain: 'Cloud Architecture & Backend',
    description: 'Work with our core infrastructure team building next-generation distributed caching and low-latency gRPC services handling over 10M daily transactions.',
    responsibilities: [
      'Design, implement, and benchmark asynchronous worker pools in Go and Node.js',
      'Optimize Redis clusters and distributed locking algorithms',
      'Instrument monitoring metrics using Prometheus and Grafana dashboards',
      'Participate in weekly code reviews and architecture design documents',
    ],
    requirements: [
      'B.Tech / B.E. in Computer Science or related engineering discipline',
      'Strong grasp of data structures, concurrency, and operating system internals',
      'Proficiency in TypeScript/JavaScript or Go',
      'Minimum CGPA of 7.5 or equivalent GitHub project portfolio',
    ],
    skillsRequired: ['TypeScript', 'Node.js', 'Docker', 'Redis', 'PostgreSQL'],
    mentorAssigned: 'Vikramaditya Sengupta (VP Engineering)',
    postedDate: '2026-08-25',
  },
  {
    id: 'int-2',
    title: 'Generative AI & Multimodal Agent Intern',
    company: 'Tata Advanced AI Research Labs',
    companyLogo: 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=100&auto=format&fit=crop&q=80',
    location: 'Pune / On-site',
    type: 'On-site',
    duration: '3 Months (Aug 2026 - Nov 2026)',
    stipend: '₹50,000 / month',
    openings: 5,
    deadline: '2026-09-28',
    domain: 'Artificial Intelligence',
    description: 'Collaborate with senior research scientists building enterprise multimodal agents capable of document understanding, tabular reasoning, and automated workflow execution.',
    responsibilities: [
      'Develop evaluation harnesses for fine-tuned open-source LLMs',
      'Build hybrid vector search indexing pipelines with dense and sparse embeddings',
      'Optimize batch inference latency using TensorRT-LLM and ONNX',
    ],
    requirements: [
      'Hands-on experience with PyTorch, HuggingFace transformers, and vector databases',
      'Familiarity with prompt engineering and LangChain or LangGraph',
      'Solid foundations in linear algebra and statistics',
    ],
    skillsRequired: ['Python', 'PyTorch', 'Vector DBs', 'RAG Pipelines', 'FastAPI'],
    mentorAssigned: 'Dr. Radhika Kulkarni (Chief Scientist)',
    postedDate: '2026-08-28',
  },
  {
    id: 'int-3',
    title: 'Industrial IoT & Telematics Embedded Firmware Intern',
    company: 'Ather Mobility Dynamics',
    companyLogo: 'https://images.unsplash.com/photo-1558981806-ec527fa84c39?w=100&auto=format&fit=crop&q=80',
    location: 'Bengaluru / On-site',
    type: 'On-site',
    duration: '6 Months',
    stipend: '₹40,000 / month',
    openings: 6,
    deadline: '2026-10-05',
    domain: 'Embedded Systems & IoT',
    description: 'Work alongside firmware engineers writing high-reliability C/C++ code for real-time electric vehicle telemetry, battery management systems, and CAN bus protocols.',
    responsibilities: [
      'Write embedded C firmware for ARM Cortex-M microcontrollers',
      'Interface sensor telemetry over I2C, SPI, and CAN protocols',
      'Conduct hardware-in-the-loop (HIL) automated test harness runs',
    ],
    requirements: [
      'Degree in ECE, EEE, or CSE with strong interest in hardware-software interfaces',
      'Fluency in C/C++ and micro-controller peripherals',
    ],
    skillsRequired: ['Embedded C', 'RTOS', 'CAN Bus', 'Python scripting', 'Git'],
    mentorAssigned: 'Sanjay Nair (Staff Firmware Architect)',
    postedDate: '2026-08-22',
  },
  {
    id: 'int-4',
    title: 'Frontend Platform & Web Performance Intern',
    company: 'Zoho Corporation Labs',
    companyLogo: 'https://images.unsplash.com/photo-1497215728101-856f4ea42174?w=100&auto=format&fit=crop&q=80',
    location: 'Chennai / Hybrid',
    type: 'Hybrid',
    duration: '4 Months',
    stipend: '₹35,000 / month',
    openings: 12,
    deadline: '2026-09-25',
    domain: 'Frontend Engineering',
    description: 'Join the product engineering group crafting ultra-responsive web applications used by 100M+ global enterprise customers.',
    responsibilities: [
      'Build reusable, accessible UI component primitives with React and Tailwind CSS',
      'Optimize Core Web Vitals (LCP, INP, CLS) across heavy data table views',
      'Write comprehensive unit and integration tests using Vitest and Testing Library',
    ],
    requirements: [
      'Deep understanding of JavaScript event loop, DOM, and CSS layout algorithms',
      'Strong React component modeling intuition',
    ],
    skillsRequired: ['React', 'TypeScript', 'Tailwind CSS', 'Web Performance', 'REST APIs'],
    mentorAssigned: 'Karthik Subramanian (Principal Architect)',
    postedDate: '2026-08-20',
  },
];

export const mockJobs: JobOpportunity[] = [
  {
    id: 'job-1',
    title: 'Graduate Engineer Trainee - Distributed Software',
    company: 'Bharat Cloud & AI Innovations Ltd.',
    companyLogo: 'https://images.unsplash.com/photo-1516321318423-f06f85e504b3?w=100&auto=format&fit=crop&q=80',
    location: 'Bengaluru / Hyderabad',
    jobType: 'Graduate Engineer Trainee',
    ctc: '₹14.5 LPA (Fixed ₹12.0 LPA + Performance Bonus ₹2.5 LPA)',
    eligibilityCgpa: 7.5,
    eligibleBranches: ['Computer Science', 'Information Technology', 'AI & Data Science', 'Electronics & Comm.'],
    deadline: '2026-10-15',
    description: 'Full-time graduate placement opportunity for the graduating batch of 2027/2026. Rapid mentorship track rotating across Core Backend, Cloud Infrastructure, and Data Engineering.',
    skillsRequired: ['Data Structures & Algorithms', 'Node.js / Java / Go', 'SQL & RDBMS', 'Computer Networks', 'Cloud Basics'],
    selectionProcess: [
      'Round 1: National AICTE Online Aptitude & Coding Test (90 Mins)',
      'Round 2: Technical Interview I (Problem Solving & DSA)',
      'Round 3: Technical Interview II (System Design & Project Defense)',
      'Round 4: Leadership & Cultural Fitment Discussion',
    ],
    openings: 35,
  },
  {
    id: 'job-2',
    title: 'Associate Machine Learning Scientist',
    company: 'Tata Advanced AI Research Labs',
    companyLogo: 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=100&auto=format&fit=crop&q=80',
    location: 'Bengaluru / Pune',
    jobType: 'Specialist',
    ctc: '₹18.0 LPA - ₹22.0 LPA',
    eligibilityCgpa: 8.0,
    eligibleBranches: ['Computer Science', 'AI & Data Science', 'Computational Sciences'],
    deadline: '2026-10-10',
    description: 'High-impact full-time role developing generative AI and industrial intelligence models for national manufacturing, energy grids, and mobility.',
    skillsRequired: ['Python', 'Deep Learning', 'PyTorch / JAX', 'NLP / Computer Vision', 'Model Optimization'],
    selectionProcess: [
      'Round 1: ML Fundamentals & Code Screen',
      'Round 2: Machine Learning Architecture & Paper Discussion',
      'Round 3: Live Coding & Debugging Challenge',
      'Round 4: HR & Offer Rollout',
    ],
    openings: 15,
  },
  {
    id: 'job-3',
    title: 'Cloud DevOps & Platform Reliability Engineer',
    company: 'Infosys Cloud & Digital Solutions',
    companyLogo: 'https://images.unsplash.com/photo-1498050108023-c5249f4df085?w=100&auto=format&fit=crop&q=80',
    location: 'Bengaluru / Chennai / Pune',
    jobType: 'Full-time',
    ctc: '₹11.0 LPA - ₹13.5 LPA',
    eligibilityCgpa: 7.0,
    eligibleBranches: ['All Engineering Branches with verified Cloud Assessment Score > 75%'],
    deadline: '2026-10-20',
    description: 'Ensure 99.99% availability for enterprise banking and digital commerce platforms with automated CI/CD and self-healing infrastructure.',
    skillsRequired: ['Linux Administration', 'Docker & Kubernetes', 'Terraform', 'CI/CD Pipelines', 'Python/Bash'],
    selectionProcess: [
      'Round 1: Online Technical Assessment',
      'Round 2: Live Troubleshooting & Linux CLI Round',
      'Round 3: Architecture & Security Review',
      'Round 4: HR Interview',
    ],
    openings: 45,
  },
];

export const mockInternshipApplications: InternshipApplication[] = [
  {
    id: 'app-int-1',
    internshipId: 'int-1',
    internshipTitle: 'Cloud Systems & Distributed Cache Engineering Intern',
    company: 'Bharat Cloud & AI Innovations Ltd.',
    appliedDate: '2026-08-26',
    status: 'Interview Scheduled',
    interviewDate: '2026-09-12 11:00 AM IST (Virtual Round 2)',
    stipend: '₹45,000 / month',
    mode: 'Hybrid',
    notes: 'Shortlisted based on high verified skill score in Node.js & Distributed Systems (88%). Mentor Vikramaditya Sengupta assigned.',
  },
  {
    id: 'app-int-2',
    internshipId: 'int-2',
    internshipTitle: 'Generative AI & Multimodal Agent Intern',
    company: 'Tata Advanced AI Research Labs',
    appliedDate: '2026-08-29',
    status: 'Under Review',
    stipend: '₹50,000 / month',
    mode: 'On-site',
    notes: 'Application forwarded to Dr. Radhika Kulkarni. Skill assessment test cleared with 91%.',
  },
  {
    id: 'app-int-3',
    internshipId: 'int-4',
    internshipTitle: 'Frontend Platform & Web Performance Intern',
    company: 'Zoho Corporation Labs',
    appliedDate: '2026-08-22',
    status: 'Offer Extended',
    stipend: '₹35,000 / month',
    mode: 'Hybrid',
    notes: 'Official Offer letter received. Pending university NOC clearance in Academia portal.',
  },
];

export const mockPlacementApplications: PlacementApplication[] = [
  {
    id: 'app-plc-1',
    jobId: 'job-1',
    jobTitle: 'Graduate Engineer Trainee - Distributed Software',
    company: 'Bharat Cloud & AI Innovations Ltd.',
    ctc: '₹14.5 LPA',
    appliedDate: '2026-08-30',
    currentRound: 'Technical Round 1',
    overallStatus: 'In Progress',
    nextRoundDate: '2026-09-15 02:30 PM IST',
  },
  {
    id: 'app-plc-2',
    jobId: 'job-2',
    jobTitle: 'Associate Machine Learning Scientist',
    company: 'Tata Advanced AI Research Labs',
    ctc: '₹20.0 LPA',
    appliedDate: '2026-09-01',
    currentRound: 'Online Aptitude',
    overallStatus: 'In Progress',
    nextRoundDate: '2026-09-18 10:00 AM IST',
  },
];

export const mockWeeklyLogs: WeeklyProgressLog[] = [
  {
    id: 'log-w1',
    internshipTitle: 'Cloud Systems & Distributed Cache Engineering Intern',
    company: 'Bharat Cloud & AI Innovations Ltd.',
    weekNumber: 1,
    period: 'Week 1: Aug 04 - Aug 08, 2026',
    tasksCompleted: 'Onboarded to monorepo, set up local Dockerized microservices mesh, and reproduced test cache stampede simulation.',
    deliverablesUrl: 'https://github.com/bharat-cloud/core-cache/pull/342',
    hoursWorked: 38,
    mentorRating: 5,
    mentorFeedback: 'Outstanding speed in setting up development containers and understanding the Raft consensus pipeline.',
    mentorName: 'Vikramaditya Sengupta',
    status: 'Approved',
  },
  {
    id: 'log-w2',
    internshipTitle: 'Cloud Systems & Distributed Cache Engineering Intern',
    company: 'Bharat Cloud & AI Innovations Ltd.',
    weekNumber: 2,
    period: 'Week 2: Aug 11 - Aug 15, 2026',
    tasksCompleted: 'Implemented probabilistic early expiration algorithm (XFetch) to eliminate cache stampedes under peak synthetic loads.',
    deliverablesUrl: 'https://github.com/bharat-cloud/core-cache/pull/356',
    hoursWorked: 42,
    mentorRating: 5,
    mentorFeedback: 'Impressive mathematical rigor! Benchmark showed a 38% latency reduction at 99th percentile. Keep up this standard.',
    mentorName: 'Vikramaditya Sengupta',
    status: 'Approved',
  },
  {
    id: 'log-w3',
    internshipTitle: 'Cloud Systems & Distributed Cache Engineering Intern',
    company: 'Bharat Cloud & AI Innovations Ltd.',
    weekNumber: 3,
    period: 'Week 3: Aug 18 - Aug 22, 2026',
    tasksCompleted: 'Instrumented OpenTelemetry spans across gRPC endpoints and created Prometheus alerting rules for cache hit-ratio drop.',
    deliverablesUrl: 'https://github.com/bharat-cloud/core-cache/pull/381',
    hoursWorked: 40,
    mentorRating: 4,
    mentorFeedback: 'Good observability metrics. Please ensure documentation on alerting thresholds is updated in the internal Confluence.',
    mentorName: 'Vikramaditya Sengupta',
    status: 'Approved',
  },
];

export const mockNotifications: AppNotification[] = [
  {
    id: 'notif-1',
    title: 'Placement Interview Scheduled',
    message: 'Bharat Cloud has scheduled your Technical Round 1 on Sep 12, 11:00 AM IST. Please test your audio and screen share.',
    timestamp: '15 mins ago',
    category: 'Placement',
    isRead: false,
    actionTarget: 'My Applications',
  },
  {
    id: 'notif-2',
    title: 'Weekly Internship Log Approved',
    message: 'Mentor Vikramaditya Sengupta approved your Week 3 deliverables with a 4.8/5.0 rating and feedback.',
    timestamp: '2 hours ago',
    category: 'Internship',
    isRead: false,
    actionTarget: 'Internship Progress & Mentor Feedback',
  },
  {
    id: 'notif-3',
    title: 'New Skill Assessment Available',
    message: 'National Cloud Native Assessment 2026 is now live. Earn a verified AICTE gold badge upon completion.',
    timestamp: 'Yesterday',
    category: 'Assessment',
    isRead: true,
    actionTarget: 'Skill Assessment',
  },
  {
    id: 'notif-4',
    title: 'University NOC Approved',
    message: 'Dean Dr. Meenakshi Sundaram has digitally signed and approved your 6-month industry internship NOC.',
    timestamp: '2 days ago',
    category: 'Academic',
    isRead: true,
    actionTarget: 'Documents',
  },
  {
    id: 'notif-5',
    title: 'SIH 2026 Problem Statement 26044 Milestone',
    message: 'Industry-Academia collaboration milestone phase 2 is active. 14 new corporate live projects added.',
    timestamp: '3 days ago',
    category: 'System',
    isRead: true,
    actionTarget: 'Mentorship & Live Projects',
  },
];

export const mockDocuments: PortalDocument[] = [
  {
    id: 'doc-1',
    title: 'Official Academic Transcript (Semesters 1-5)',
    category: 'Transcript',
    uploadedDate: '2026-08-10',
    fileSize: '1.8 MB',
    verifiedBy: 'NIT Trichy Registrar Office',
    status: 'Verified',
  },
  {
    id: 'doc-2',
    title: 'AICTE Industrial Internship NOC Clearance Letter',
    category: 'NOC',
    uploadedDate: '2026-08-24',
    fileSize: '640 KB',
    verifiedBy: 'Dr. Meenakshi Sundaram (Dean)',
    status: 'Verified',
  },
  {
    id: 'doc-3',
    title: 'SIH 2026 Verified Candidate Competency Dossier',
    category: 'Resume',
    uploadedDate: '2026-09-01',
    fileSize: '950 KB',
    verifiedBy: 'National Skill Registry 26044',
    status: 'Verified',
  },
  {
    id: 'doc-4',
    title: 'Industry-University R&D MoU (NIT Trichy & Bharat Cloud)',
    category: 'MoU',
    uploadedDate: '2026-07-15',
    fileSize: '4.2 MB',
    verifiedBy: 'Ministry of Education & Industry Liaison',
    status: 'Verified',
  },
  {
    id: 'doc-5',
    title: 'Zoho Corporation Provisional Internship Offer Letter',
    category: 'Internship Certificate',
    uploadedDate: '2026-08-25',
    fileSize: '512 KB',
    verifiedBy: 'Zoho Talent Acquisition',
    status: 'Verified',
  },
];

export const mockCandidates: CandidateCandidate[] = [
  {
    id: 'cand-1',
    name: 'Aarav Sharma',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    college: 'NIT Trichy',
    department: 'Computer Science',
    graduationYear: 2027,
    cgpa: 8.82,
    skillReadinessScore: 92,
    topSkills: ['React', 'Node.js', 'PostgreSQL', 'Docker', 'System Design'],
    projectsCount: 5,
    internshipsCompleted: 1,
    preferredRole: 'Full Stack Cloud Engineer',
    locationPreference: 'Bengaluru, Hyderabad, Remote',
    status: 'Interviewing',
  },
  {
    id: 'cand-2',
    name: 'Priyanka Nambiar',
    avatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=150&auto=format&fit=crop&q=80',
    college: 'IIT Madras',
    department: 'Data Science & AI',
    graduationYear: 2027,
    cgpa: 9.15,
    skillReadinessScore: 95,
    topSkills: ['PyTorch', 'Vector DBs', 'FastAPI', 'RAG Pipelines', 'Computer Vision'],
    projectsCount: 7,
    internshipsCompleted: 2,
    preferredRole: 'AI Research Scientist',
    locationPreference: 'Bengaluru, Chennai',
    status: 'Available',
  },
  {
    id: 'cand-3',
    name: 'Rohan Deshmukh',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
    college: 'BITS Pilani',
    department: 'Electrical & Electronics',
    graduationYear: 2026,
    cgpa: 8.45,
    skillReadinessScore: 87,
    topSkills: ['Embedded C', 'RTOS', 'CAN Bus', 'IoT Firmware', 'Linux'],
    projectsCount: 4,
    internshipsCompleted: 1,
    preferredRole: 'Embedded Firmware Engineer',
    locationPreference: 'Pune, Bengaluru',
    status: 'Available',
  },
  {
    id: 'cand-4',
    name: 'Sneha Roy',
    avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&auto=format&fit=crop&q=80',
    college: 'IIT Roorkee',
    department: 'Computer Science',
    graduationYear: 2026,
    cgpa: 8.94,
    skillReadinessScore: 91,
    topSkills: ['Kubernetes', 'Go', 'Prometheus', 'Terraform', 'Microservices'],
    projectsCount: 6,
    internshipsCompleted: 2,
    preferredRole: 'DevOps & SRE Engineer',
    locationPreference: 'Bengaluru, Delhi NCR',
    status: 'Interviewing',
  },
  {
    id: 'cand-5',
    name: 'Aditya Verma',
    avatar: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=150&auto=format&fit=crop&q=80',
    college: 'IIIT Hyderabad',
    department: 'Information Technology',
    graduationYear: 2027,
    cgpa: 8.65,
    skillReadinessScore: 89,
    topSkills: ['Next.js', 'TypeScript', 'GraphQL', 'Tailwind CSS', 'Redux'],
    projectsCount: 5,
    internshipsCompleted: 1,
    preferredRole: 'Frontend Platform Engineer',
    locationPreference: 'Hyderabad, Bengaluru',
    status: 'Placed',
  },
];

export const mockMentorshipProjects: LiveMentorshipProject[] = [
  {
    id: 'proj-live-1',
    title: 'High-Throughput Indic Voice Transcription for Public Service Portals',
    industryPartner: 'Bharat Cloud & AI Innovations Ltd.',
    facultyLead: 'Dr. Meenakshi Sundaram (NIT Trichy)',
    duration: '12 Weeks (SIH 2026 Cohort)',
    difficulty: 'Industry Grade',
    stipendOrGrant: '₹1,50,000 Team Research Grant',
    teamsEnrolled: 4,
    maxTeams: 6,
    description: 'Students partner directly with Bharat Cloud speech researchers to build a low-compute Indic speech recognition inference server streaming over WebSockets.',
    expectedOutcomes: [
      'Streaming WebSocket server processing audio chunks under 250ms latency',
      'Benchmark results against Whisper across Tamil, Hindi, Telugu, and Kannada',
      'Production Docker deployment guide with Kubernetes helm chart',
    ],
    skillsRequired: ['Python', 'FastAPI', 'WebSockets', 'PyTorch', 'Docker'],
    status: 'Active Mentorship',
  },
  {
    id: 'proj-live-2',
    title: 'Autonomous EV Battery State-of-Health Predictor Using Physics-Informed ML',
    industryPartner: 'Ather Mobility Dynamics',
    facultyLead: 'Dr. K. Ramaswamy (IISc Bengaluru)',
    duration: '16 Weeks',
    difficulty: 'R&D',
    stipendOrGrant: '₹2,00,000 Innovation Fellowship',
    teamsEnrolled: 3,
    maxTeams: 4,
    description: 'Combine electrochemical battery degradation models with machine learning neural ODEs to forecast remaining battery cycles from real EV ride logs.',
    expectedOutcomes: [
      'Physics-informed neural network model trained on public battery cycling datasets',
      'Inference code ready for deployment on automotive edge gateway',
      'Co-authored research paper submission for IEEE Transportation Electrification',
    ],
    skillsRequired: ['PyTorch', 'Physics-Informed ML', 'Data Analysis', 'Automotive CAN'],
    status: 'Open for Registration',
  },
  {
    id: 'proj-live-3',
    title: 'Zero-Knowledge Proof Verifier for Inter-University Credit Transfer',
    industryPartner: 'National Academic Depository & Tata Trust',
    facultyLead: 'Prof. Ananya Sen (IIT Kharagpur)',
    duration: '10 Weeks',
    difficulty: 'Industry Grade',
    stipendOrGrant: '₹1,20,000 Grant + Patent Filing Support',
    teamsEnrolled: 5,
    maxTeams: 5,
    description: 'Implement zk-SNARK cryptographic proofs allowing students to verify course prerequisite completion without disclosing full personal marks sheets.',
    expectedOutcomes: [
      'Circom zk-SNARK circuit for academic credit verification',
      'Solidity verifier smart contract and TypeScript verification client',
      'Interactive demonstration portal for university registrars',
    ],
    skillsRequired: ['Cryptography', 'Circom / SnarkJS', 'TypeScript', 'Web3 / Security'],
    status: 'Active Mentorship',
  },
];

export const mockTrainingPrograms: TrainingProgram[] = [
  {
    id: 'tp-1',
    title: 'National Faculty Development Program: Industry 4.0 & Cloud Microservices',
    conductedBy: 'AICTE & Bharat Cloud Engineering Guild',
    targetAudience: 'Faculty (FDP)',
    mode: 'Hybrid',
    startDate: '2026-09-20',
    duration: '2 Weeks (40 Hours)',
    registeredCount: 320,
    capacity: 400,
    aicteApproved: true,
    curriculumKeyPoints: [
      'Modern Distributed Architecture Patterns (CQRS & Event Sourcing)',
      'Integrating Industry Case Studies into Undergraduate B.Tech Syllabus',
      'Lab Setup with Cloud Sandboxes & Automated Code Grading',
      'Industry Joint Research Project Formulation',
    ],
  },
  {
    id: 'tp-2',
    title: 'Hands-on Student Bootcamp: Production Generative AI & Vector Engines',
    conductedBy: 'IIT Madras & Google for Education',
    targetAudience: 'Students',
    mode: 'Online',
    startDate: '2026-09-25',
    duration: '4 Weeks (Weekend Intensive)',
    registeredCount: 1850,
    capacity: 2500,
    aicteApproved: true,
    curriculumKeyPoints: [
      'Embedding Spaces and Vector Distance Mathematics',
      'Building Full-Stack RAG Applications from Scratch',
      'Prompt Engineering, Evaluation, and Guardrails',
      'Deploying on Cloud Run with High-Concurrency Load Tests',
    ],
  },
  {
    id: 'tp-3',
    title: 'National Cybersecurity Defense & Ethical Hacking Symposium',
    conductedBy: 'C-DAC & CERT-In Academic Cell',
    targetAudience: 'Joint',
    mode: 'Campus Workshop',
    startDate: '2026-10-02',
    duration: '3 Days',
    registeredCount: 410,
    capacity: 500,
    aicteApproved: true,
    curriculumKeyPoints: [
      'Live CTF (Capture the Flag) Attack and Defense Challenges',
      'Reverse Engineering Binaries and Memory Forensics',
      'Cloud Misconfiguration Auditing in AWS and GCP',
      'CERT-In Reporting Frameworks and Compliance',
    ],
  },
];

export const mockAcademiaStats = {
  totalStudents: 3450,
  verifiedStudents: 3120,
  overallPlacementRate: 91.4,
  averageSalaryLPA: 11.2,
  highestSalaryLPA: 48.0,
  activeInternshipsCount: 524,
  activeIndustryMoUs: 42,
  departmentStats: [
    { department: 'Computer Science & Engg', total: 720, placed: 685, avgCgpa: 8.42, readinessScore: 88 },
    { department: 'Information Technology', total: 480, placed: 440, avgCgpa: 8.25, readinessScore: 85 },
    { department: 'Data Science & AI', total: 360, placed: 342, avgCgpa: 8.65, readinessScore: 92 },
    { department: 'Electronics & Comm.', total: 600, placed: 535, avgCgpa: 8.10, readinessScore: 81 },
    { department: 'Electrical & Electronics', total: 420, placed: 365, avgCgpa: 7.95, readinessScore: 78 },
    { department: 'Mechanical & Automation', total: 870, placed: 750, avgCgpa: 7.80, readinessScore: 74 },
  ],
  industryDemandTrends: [
    { skill: 'Cloud & Microservices (K8s/Docker)', demandIndex: 96, campusCurriculumCoverage: 74, status: 'Critical Gap' },
    { skill: 'Applied GenAI & Vector Search', demandIndex: 95, campusCurriculumCoverage: 62, status: 'Critical Gap' },
    { skill: 'Full Stack Web (TypeScript/React)', demandIndex: 92, campusCurriculumCoverage: 88, status: 'Well Aligned' },
    { skill: 'Embedded Systems & CAN/RTOS', demandIndex: 82, campusCurriculumCoverage: 80, status: 'Well Aligned' },
    { skill: 'Cybersecurity & Zero-Trust', demandIndex: 89, campusCurriculumCoverage: 65, status: 'Moderate Gap' },
    { skill: 'Relational & Distributed SQL', demandIndex: 88, campusCurriculumCoverage: 91, status: 'Well Aligned' },
  ],
  topRecruiters: [
    { name: 'Bharat Cloud Innovations', offers: 54, avgPackage: '₹14.5 LPA' },
    { name: 'Tata Consultancy & AI Labs', offers: 78, avgPackage: '₹12.8 LPA' },
    { name: 'Zoho Corporation', offers: 42, avgPackage: '₹10.5 LPA' },
    { name: 'Ather Mobility', offers: 26, avgPackage: '₹13.0 LPA' },
    { name: 'Infosys Digital', offers: 92, avgPackage: '₹9.5 LPA' },
    { name: 'Qualcomm India', offers: 18, avgPackage: '₹22.0 LPA' },
  ],
};

// Aliases for unified imports
export const initialStudentProfile = mockStudentProfile;
export const initialAcademiaProfile = mockAcademiaProfile;
export const initialIndustryProfile = mockIndustryProfile;
export const initialSkillCategories = mockSkillCategories;
export const initialCareerPaths = mockCareerPaths;
export const initialLearningRecommendations = mockLearningRecommendations;
export const initialProjectShowcases = mockProjects;
export const initialInternships = mockInternships;
export const initialInternshipApplications = mockInternshipApplications;
export const initialWeeklyProgressLogs = mockWeeklyLogs;
export const initialJobPostings = mockJobs;
export const initialPlacementApplications = mockPlacementApplications;
export const initialNotifications = mockNotifications;
export const initialDocuments = mockDocuments;
export const initialCandidateSearchItems = mockCandidates;
export const sampleSkillQuestions = mockAssessmentQuestions;

export const initialDepartmentAnalytics = [
  {
    department: 'Computer Science & Engineering',
    studentCount: 720,
    avgSkillScore: 88,
    placementPct: 95.1,
    topSkillGap: 'Cloud Native & Kubernetes',
    avgPackage: '₹16.2 LPA',
  },
  {
    department: 'Information Technology',
    studentCount: 480,
    avgSkillScore: 85,
    placementPct: 91.6,
    topSkillGap: 'Distributed Microservices',
    avgPackage: '₹14.8 LPA',
  },
  {
    department: 'Electronics & Communication',
    studentCount: 600,
    avgSkillScore: 81,
    placementPct: 89.2,
    topSkillGap: 'Edge ML & Embedded Firmware',
    avgPackage: '₹12.4 LPA',
  },
  {
    department: 'Mechanical & Mechatronics',
    studentCount: 870,
    avgSkillScore: 74,
    placementPct: 86.2,
    topSkillGap: 'Robotics Control & ROS2',
    avgPackage: '₹9.8 LPA',
  },
];

export const initialIndustrySkillDemands = [
  {
    id: 'isd-1',
    skillName: 'Distributed Cloud Architecture & Kubernetes',
    domain: 'Cloud Computing',
    growthRate: '+42% YoY',
    openRequisitions: 14200,
    academicSupply: 'Critical Deficit',
    topHiringCompanies: ['Bharat Cloud', 'Google India', 'Microsoft', 'Oracle Cloud'],
    avgPackage: '₹18.5 LPA',
  },
  {
    id: 'isd-2',
    skillName: 'Generative AI & LLM Systems (RAG / LoRA)',
    domain: 'Artificial Intelligence',
    growthRate: '+68% YoY',
    openRequisitions: 18400,
    academicSupply: 'Critical Deficit',
    topHiringCompanies: ['Tata AI Labs', 'NVIDIA', 'Infosys Digital', 'Wipro AI'],
    avgPackage: '₹22.0 LPA',
  },
  {
    id: 'isd-3',
    skillName: 'Industrial IoT & Automotive CAN Systems',
    domain: 'Robotics & Hardware',
    growthRate: '+28% YoY',
    openRequisitions: 8900,
    academicSupply: 'Moderate Deficit',
    topHiringCompanies: ['Ather Mobility', 'Bosch India', 'Tata Motors', 'Ola Electric'],
    avgPackage: '₹13.2 LPA',
  },
  {
    id: 'isd-4',
    skillName: 'Enterprise Zero-Trust & API Security',
    domain: 'Cybersecurity',
    growthRate: '+34% YoY',
    openRequisitions: 11200,
    academicSupply: 'Critical Deficit',
    topHiringCompanies: ['Cisco Systems', 'Palo Alto Networks', 'Zoho', 'Quick Heal'],
    avgPackage: '₹15.8 LPA',
  },
];

export const initialTrainingPrograms = [
  {
    id: 'tp-1',
    title: 'Distributed Cloud Engineering & Kubernetes Mastery',
    partnerCompany: 'Bharat Cloud & AI Innovations',
    domain: 'Distributed Cloud Computing',
    duration: '8 Weeks',
    enrolledCount: 118,
    maxCapacity: 150,
    instructor: 'Dr. Meenakshi Sundaram',
    creditsAwarded: 3,
    status: 'Active',
    startDate: 'Sep 2026',
  },
  {
    id: 'tp-2',
    title: 'Enterprise Generative AI & Vector Pipeline Co-Op',
    partnerCompany: 'Tata Advanced AI Research Labs',
    domain: 'Applied Artificial Intelligence',
    duration: '10 Weeks',
    enrolledCount: 142,
    maxCapacity: 150,
    instructor: 'Dr. Radhika Kulkarni',
    creditsAwarded: 4,
    status: 'Active',
    startDate: 'Sep 2026',
  },
];

export const initialFdpPrograms = [
  {
    id: 'fdp-1',
    title: 'Industry 4.0: Modern Distributed Microservices & DevOps for Engineering Faculty',
    sponsor: 'AICTE & Bharat Cloud Guild',
    duration: '2 Weeks (40 Hours)',
    startDate: 'Sep 20, 2026',
    facultyEnrolled: 320,
  },
  {
    id: 'fdp-2',
    title: 'National AICTE FDP on Generative AI & Quantum Computing Foundations',
    sponsor: 'IIT Madras & Google for Education',
    duration: '1 Week Intensive',
    startDate: 'Oct 04, 2026',
    facultyEnrolled: 245,
  },
];

export const initialLiveProjects = [
  {
    id: 'lp-1',
    title: 'High-Throughput Indic Voice Transcription Server',
    company: 'Bharat Cloud & AI Innovations Ltd.',
    mentorName: 'Vikramaditya Sengupta',
    domain: 'Cloud Infrastructure & AI',
    duration: '10 Weeks',
    enrolledStudents: 6,
    maxSlots: 8,
    techStack: ['Python', 'FastAPI', 'WebSockets', 'PyTorch', 'Docker'],
    description: 'Build a low-compute Indic speech recognition inference server streaming over WebSockets under 250ms latency.',
    status: 'Active',
    progressPercentage: 65,
    nextDeliverableDate: 'Sep 18, 2026',
  },
  {
    id: 'lp-2',
    title: 'EV Battery State-of-Health Neural ODE Estimator',
    company: 'Ather Mobility Dynamics',
    mentorName: 'Sanjay Nair',
    domain: 'Automotive IoT',
    duration: '12 Weeks',
    enrolledStudents: 4,
    maxSlots: 6,
    techStack: ['C++', 'Python', 'PyTorch', 'CAN Bus'],
    description: 'Combine physics degradation models with neural ODEs to forecast remaining battery cycles from vehicle ride logs.',
    status: 'Active',
    progressPercentage: 40,
    nextDeliverableDate: 'Sep 25, 2026',
  },
];

